#ifndef __CMD__
#define __CMD__

#include "Common.h"

#define SERVER_CMD_BEGIN(server_type) (server_type*100)

//common cmd
#define MSG_CMD_RPC (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+1)
#define MSG_CMD_HEARTBEAT (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+2)

//centerd cmd
#define MSG_CMD_REGISTER_GLOBAL_SERVICE (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+1)
#define MSG_CMD_REGISTER_GLOBAL_BACK (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+2)
#define MSG_CMD_CREATE_ENTIRY_ANYWHERE (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+3)

#endif //__CMD__

