#ifndef __CMD__
#define __CMD__

#include "Common.h"

//每种服类型预留128个CMD,最开始128个是通用指令
#define SERVER_CMD_BEGIN(server_type) (server_type<<8)

//common cmd
#define MSG_CMD_RPC (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+1)
#define MSG_CMD_HEARTBEAT (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+2)
#define MSG_CMD_CREATE_ENTIRY_CALLBACK (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+3)
#define MSG_CMD_SYNC_SERVER_INFO (SERVER_CMD_BEGIN(SERVER_TYPE_NULL)+4)

//centerd cmd
#define MSG_CMD_SERVER_REGISTER (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+1) //其他服向centerd注册
#define MSG_CMD_REGISTER_GLOBAL_SERVICE (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+1)
#define MSG_CMD_REGISTER_GLOBAL_BACK (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+2)
#define MSG_CMD_CREATE_ENTIRY_ANYWHERE (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+3)
#define MSG_CMD_CREATE_ENTIRY_FROM_DB_ANYWHERE (SERVER_CMD_BEGIN(SERVER_TYPE_CENTERD)+4)

//dbd cmd
#define MSG_CMD_LOAD_DATA_FROM_DB (SERVER_CMD_BEGIN(SERVER_TYPE_DBD)+1)

#define DBD_WORKER_CMD_BEGIN MSG_CMD_LOAD_DATA_FROM_DB
#define DBD_WORKER_CMD_END MSG_CMD_LOAD_DATA_FROM_DB 
#define IS_DBD_WORKER_CMD(cmd_id) ((cmd_id) >= DBD_WORKER_CMD_BEGIN && (cmd_id) <= DBD_WORKER_CMD_END)

#endif //__CMD__

